[build]
# make use of all cores for building
jobs = 8

[target.x86_64-unknown-linux-gnu]
# use clang for faster linking
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-pc-windows-msvc]
# use lld for faster linking on windows based systems
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
# replace lld with ld64 for faster linking on macOS
rustflags = ["-C", "link-arg=-fuse-ld=lld"]